#
# Vivado (TM) v2015.2 (64-bit)
#
# md5.tcl: Tcl script for re-creating project 'md5'
#
# Generated by Vivado on Thu Feb 18 15:24:40 CET 2016
# IP Build 1264090 on Wed Jun 24 14:22:01 MDT 2015
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (md5.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "/home/rolf/ntp_proj/trunk/FPGA/network_path/packet_proc/MD5/hdl/md5_stage.v"
#    "/home/rolf/ntp_proj/trunk/FPGA/network_path/packet_proc/MD5/hdl/md5_pipe.v"
#    "/home/rolf/ntp_proj/trunk/FPGA/network_path/packet_proc/MD5/ip/chunk_del_md5/chunk_del_md5.xci"
#    "/home/rolf/ntp_proj/trunk/FPGA/network_path/packet_proc/MD5/ip/sum_del_md5/sum_del_md5.xci"
#    "/home/rolf/ntp_proj/trunk/FPGA/network_path/packet_proc/MD5/hdl/md5.v"
#    "/home/rolf/ntp_proj/trunk/FPGA/network_path/packet_proc/MD5/tb/tb_md5_func.sv"
#    "/home/rolf/ntp_proj/trunk/FPGA/network_path/packet_proc/MD5/tb/tb_md5.v"
#    "/home/rolf/ntp_proj/trunk/FPGA/network_path/packet_proc/MD5/tb/tb_md5_pipe.v"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/md5"]"

# Create project
create_project md5 ./md5

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [get_projects md5]
set_property "board_part" "xilinx.com:vc709:part0:1.6" $obj
set_property "default_lib" "xil_defaultlib" $obj
set_property "simulator_language" "Mixed" $obj
set_property "target_simulator" "Questa" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../hdl/md5_stage.v"]"\
 "[file normalize "$origin_dir/../hdl/md5_pipe.v"]"\
 "[file normalize "$origin_dir/../ip/chunk_del_md5/chunk_del_md5.xci"]"\
 "[file normalize "$origin_dir/../ip/sum_del_md5/sum_del_md5.xci"]"\
 "[file normalize "$origin_dir/../hdl/md5.v"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/../ip/chunk_del_md5/chunk_del_md5.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property "synth_checkpoint_mode" "Singular" $file_obj
}

set file "$origin_dir/../ip/sum_del_md5/sum_del_md5.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property "synth_checkpoint_mode" "Singular" $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "top" "md5" $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Empty (no sources present)

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
set files [list \
 "[file normalize "$origin_dir/../tb/tb_md5_func.sv"]"\
 "[file normalize "$origin_dir/../tb/tb_md5.v"]"\
 "[file normalize "$origin_dir/../tb/tb_md5_pipe.v"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sim_1' fileset file properties for remote files
set file "$origin_dir/../tb/tb_md5_func.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj


# Set 'sim_1' fileset file properties for local files
# None

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "questa.compile.vlog.more_options" "-sv" $obj
set_property "runtime" "" $obj
set_property "top" "tb_md5" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7vx690tffg1761-2 -flow {Vivado Synthesis 2015} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2015" [get_runs synth_1]
}
set obj [get_runs synth_1]

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7vx690tffg1761-2 -flow {Vivado Implementation 2015} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2015" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property "steps.write_bitstream.args.readback_file" "0" $obj
set_property "steps.write_bitstream.args.verbose" "0" $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:md5"
