set_property PACKAGE_PIN H19 [get_ports SYS_CLK_P]
set_property IOSTANDARD DIFF_SSTL15 [get_ports SYS_CLK_P]
create_clock -period 10.000 -name SYS_CLK -waveform {0.000 5.000} [get_ports SYS_CLK_P]

set_property IOSTANDARD LVCMOS18 [get_ports i2c_scl]
set_property SLEW SLOW [get_ports i2c_scl]
set_property DRIVE 16 [get_ports i2c_scl]
set_property PULLUP true [get_ports i2c_scl]
set_property PACKAGE_PIN AT35 [get_ports i2c_scl]

set_property IOSTANDARD LVCMOS18 [get_ports i2c_sda]
set_property SLEW SLOW [get_ports i2c_sda]
set_property DRIVE 16 [get_ports i2c_sda]
set_property PULLUP true [get_ports i2c_sda]
set_property PACKAGE_PIN AU32 [get_ports i2c_sda]

set_property IOSTANDARD LVCMOS18 [get_ports i2c_mux_rst_n]
set_property SLEW SLOW [get_ports i2c_mux_rst_n]
set_property DRIVE 16 [get_ports i2c_mux_rst_n]
set_property PACKAGE_PIN AY42 [get_ports i2c_mux_rst_n]

set_property IOSTANDARD LVCMOS18 [get_ports si5324_rst_n]
set_property SLEW SLOW [get_ports si5324_rst_n]
set_property DRIVE 16 [get_ports si5324_rst_n]
set_property PACKAGE_PIN AT36 [get_ports si5324_rst_n]

# set_property PACKAGE_PIN AM39 [get_ports LED0]
# set_property IOSTANDARD LVCMOS18 [get_ports LED0]
# set_property PACKAGE_PIN AN39 [get_ports LED1]
# set_property IOSTANDARD LVCMOS18 [get_ports LED1]
# set_property PACKAGE_PIN AR37 [get_ports LED2]
# set_property IOSTANDARD LVCMOS18 [get_ports LED2]
# set_property PACKAGE_PIN AT37 [get_ports LED3]
# set_property IOSTANDARD LVCMOS18 [get_ports LED3]
# set_property PACKAGE_PIN AR35 [get_ports LED4]
# set_property IOSTANDARD LVCMOS18 [get_ports LED4]
# set_property PACKAGE_PIN AP41 [get_ports LED5]
# set_property IOSTANDARD LVCMOS18 [get_ports LED5]
# set_property PACKAGE_PIN AP42 [get_ports LED6]
# set_property IOSTANDARD LVCMOS18 [get_ports LED6]
# set_property PACKAGE_PIN AU39 [get_ports LED7]
# set_property IOSTANDARD LVCMOS18 [get_ports LED7]

#As per UG470, UG899, UG908, and G18 Flash specifications
set_property BITSTREAM.CONFIG.BPI_SYNC_MODE Type1 [current_design]
set_property BITSTREAM.CONFIG.EXTMASTERCCLK_EN div-1 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN Pulldown [current_design]
set_property CONFIG_MODE BPI16 [current_design]
set_property CFGBVS GND [current_design]
set_property CONFIG_VOLTAGE 1.8 [current_design]
